parameters:
    tables:
        acl_groups: '%core.table_prefix%acl_groups'
        acl_options: '%core.table_prefix%acl_options'
        acl_roles_data: '%core.table_prefix%acl_roles_data'
        acl_roles: '%core.table_prefix%acl_roles'
        acl_users: '%core.table_prefix%acl_users'
        attachments: '%core.table_prefix%attachments'
        banlist: '%core.table_prefix%banlist'
        bbcodes: '%core.table_prefix%bbcodes'
        bookmarks: '%core.table_prefix%bookmarks'
        bots: '%core.table_prefix%bots'
        config: '%core.table_prefix%config'
        config_text: '%core.table_prefix%config_text'
        confirm: '%core.table_prefix%confirm'
        disallow: '%core.table_prefix%disallow'
        drafts: '%core.table_prefix%drafts'
        ext: '%core.table_prefix%ext'
        extesnions: '%core.table_prefix%extesnions'
        extension_groups': '%core.table_prefix%extension_groups'
        forums: '%core.table_prefix%forums'
        forums_access: '%core.table_prefix%forums_access'
        forums_track: '%core.table_prefix%forums_track'
        forums_watch: '%core.table_prefix%forums_watch'
        groups: '%core.table_prefix%groups'
        icons: '%core.table_prefix%icons'
        lang: '%core.table_prefix%lang'
        log: '%core.table_prefix%log'
        login_attempts: '%core.table_prefix%login_attempts'
        migrations: '%core.table_prefix%migrations'
        moderator_cache: '%core.table_prefix%moderator_cache'
        modules: '%core.table_prefix%modules'
        notification_types: '%core.table_prefix%notification_types'
        notifications: '%core.table_prefix%notifications'
        poll_options: '%core.table_prefix%poll_options'
        poll_votes: '%core.table_prefix%poll_votes'
        posts: '%core.table_prefix%posts'
        privmsgs: '%core.table_prefix%privmsgs'
        privmsgs_folder: '%core.table_prefix%privmsgs_folder'
        privmsgs_rules: '%core.table_prefix%privmsgs_rules'
        privmsgs_to: '%core.table_prefix%privmsgs_to'
        profile_fields: '%core.table_prefix%profile_fields'
        profile_fields_data: '%core.table_prefix%profile_fields_data'
        profile_fields_lang: '%core.table_prefix%profile_fields_lang'
        profile_lang: '%core.table_prefix%profile_lang'
        ranks: '%core.table_prefix%ranks'
        reports: '%core.table_prefix%reports'
        reports_reasons: '%core.table_prefix%reports_reasons'
        search_results: '%core.table_prefix%search_results'
        search_wordlist: '%core.table_prefix%search_wordlist'
        search_wordmatch: '%core.table_prefix%search_wordmatch'
        sessions: '%core.table_prefix%sessions'
        sessions_keys: '%core.table_prefix%sessions_keys'
        sitelist: '%core.table_prefix%sitelist'
        smilies: '%core.table_prefix%smilies'
        sphinx: '%core.table_prefix%sphinx'
        styles: '%core.table_prefix%styles'
        styles_template: '%core.table_prefix%styles_template'
        styles_template_data: '%core.table_prefix%styles_template_data'
        styles_theme: '%core.table_prefix%styles_theme'
        styles_imageset: '%core.table_prefix%styles_imageset'
        styles_imageset_data: '%core.table_prefix%styles_imageset_data'
        teampage: '%core.table_prefix%teampage'
        topics: '%core.table_prefix%topics'
        topics_posted: '%core.table_prefix%topics_posted'
        topics_track: '%core.table_prefix%topics_track'
        topics_watch: '%core.table_prefix%topics_watch'
        user_group: '%core.table_prefix%user_group'
        user_notifications: '%core.table_prefix%user_notifications'
        users: '%core.table_prefix%users'
        warnings: '%core.table_prefix%warnings'
        words: '%core.table_prefix%words'
        zebra: '%core.table_prefix%zebra'
