imports:
    - { resource: userdetails_constants.yml }
    - { resource: arraydata.yml }

services:
    david63.userdetails.data.controller:
        class: david63\userdetails\controller\data_controller
        arguments:
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@pagination'
            - '@user'
            - '@group_helper'
            - '@language'
            - '@profilefields.type_collection'
            - '@david63.userdetails.core.functions'
            - '%select_ary%'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables%'
            - '%constants%'

    david63.userdetails.core.functions:
        class: david63\userdetails\core\functions
        arguments:
            - '@ext.manager'
